### ISSUE TITLE
Product list in Admin 

### ISSUE THREAD

**Issue by ChristianGiupponi** [firesale/firesale#91] opened 2012-09-18 07:47 UTC
When I add a product in the list of producs doesn't show up the image of the product.
Same thing appen in the site when I visit the product page.

See: http://www.diigo.com/item/image/32ya3/ruop
and: http://www.diigo.com/item/image/32ya3/hc7e

for now I will add all the issues I found, tomorrow I have an exam at university so today I can't find a possibile fix, from this weekend I can help much more!

**Comment by jHoldroyd** [comment] 2012-09-18 19:33
Can you clear your browser cache and check it again. If it's not any better check the source of the page and post the URL of the image it's trying to load.

**Comment by yllumi** [comment] 2012-09-20 11:09
maybe christian mean like this:
http://d.pr/i/q3jL
image uploaded successfuly, but it doesn't appear in product list.

then I search and found this line in firesale/views/admin/products/index.php :

```
<td class="item-img"><img src="<?php echo ( $product['image'] != FALSE ? '/files/thumb/' . $product['image'] . '/32/32' : '' ); ?>" alt="Product Image" /></td>
```

and everything okay after I made changes to this:

```
<td class="item-img"><img src="<?php echo ( $product['image'] != FALSE ? site_url('files/thumb/' . $product['image'] . '/32/32') : '' ); ?>" alt="Product Image" /></td>
```

I found same thing in some places. I guess it happened in local only,

**Comment by jHoldroyd** [comment] 2012-09-20 15:36
Thanks for that, I think I know what the root cause of the issue was and I'm going to presume you were both running in a sub-directory! It should be fixed now so I'm closing this now

**Closed as completed by jHoldroyd** 2012-09-20 15:36 UTC
Labels: Bug
