### ISSUE TITLE
Manage categories

### ISSUE THREAD

**Issue by from2day** [firesale/firesale#24] opened 2012-07-30 12:29 UTC
During category edit, there is the same form of adding category. After pressing "Add category" and selecting "renewed" category error pops out: 
Error: The server is not responding correctly, please try again later.

**Comment by ChristianGiupponi** [comment] 2012-07-30 12:46
Same issue, and there is no "Delete button"

**Comment by jHoldroyd** [comment] 2012-07-30 13:41
I'm not sure if you're trying to delete/remove category 1, for a number of reasons we disabled this but if that's not the case it's something I will look into for you soon.

**Comment by jHoldroyd** [comment] 2012-07-30 19:31
Pafbone could you please post the exact data you're using in your category fields so I can test it? Currently I'm having trouble replicating that error.

Christian I've just pushed a fix that should show the right buttons in each context (eg edit/delete wern't showing after a submit with failed validation, etc.) That should all be fixed but I'd like to get to the root cause of the ajax error before closing this fully.

**Comment by from2day** [comment] 2012-07-31 11:28
After "multiple" field installation and fresh latest FireSALE version, bug doesn't appear. I guess that was because of my field-hack.

**Comment by jHoldroyd** [comment] 2012-07-31 18:02
Just merged a new readme to cover this requirement, thanks for reporting it.

**Closed as completed by jHoldroyd** 2012-07-31 18:02 UTC
