### ISSUE TITLE
2.2 compatibility

### ISSUE THREAD

**Issue by chrisnharvey** [firesale/firesale#266] opened 2013-01-17 10:50 UTC
We need to move the hacky FireSale menu which I wrote a while back to the new PyroCMS menu method in the details.php file whilst still maintaining 2.1.x compatibility.

**Comment by jHoldroyd** [comment] 2013-01-17 21:53
I've just gotten the base menu structure in place, still some work left to do to remove the old hacks and the bits of the library that were responsible for the old menu but it's a good start so far.

**Comment by jHoldroyd** [comment] 2013-01-21 12:03
We're also now totally tied into the search indexes for both front and backend searching

**Comment by jHoldroyd** [comment] 2013-03-04 16:40
I think the last things left to do on this are fixing the menu structure and that's about it.

**Comment by jHoldroyd** [comment] 2013-03-04 16:40
Didn't mean to close that!

**Comment by yveveke** [comment] 2013-03-06 11:34
@jHoldroyd in your last commit you deleted the function info() from the firesale library.
The modules "brands", "search", and "shipping" still use it in their detail.php file.

I'm new in using Github, so I made a comment on the line where the function starts, and post it here.

**Comment by jHoldroyd** [comment] 2013-03-06 12:41
I've started to strip out a lot of "hacks" we did in the start to get things merged together. I'll get this fixed in the next hour or so though

**Comment by yveveke** [comment] 2013-03-07 09:58
Another bug caused by the cleanup:

``` php
Fatal error: Call to undefined method Firesale::register_elements() in [stripped]addons/shared_addons/modules/firesale/libraries/firesale.php on line 111
```

**Closed as completed** 2013-03-15 10:58 UTC
Labels: Update
