### ISSUE TITLE
Product Variations

### ISSUE THREAD

**Issue by Dev7** [firesale/firesale#156] opened 2012-10-30 22:39 UTC
Great start! Love the modules. I think it has all the basics you would see in a product/cart module. The one thing that is a basic feature that seems to be missing is product variations. LOVE THE MODULES!!!

**Comment by jHoldroyd** [comment] 2012-10-30 22:52
Thanks for the comments and it's coming, it's carved in stone to be in 1.2...I tried to get it into 1.1 but we kinda had enough to do and called it off. But it's definitely coming, we toyed with the idea of using our (in development) attributes module for product variations and if you check http://www.shelikesitmini.co.uk/product/chloe that's how we did it for there, but it's not a great solution in the long term.

**Comment by Dev7** [comment] 2012-10-30 23:12
FAST response. Thanks... Glad to see it is coming in 1.2!

**Comment by jHoldroyd** [comment] 2012-10-30 23:49
Yeah we're aiming to have 1.2 ready for Pyro 2.2s release so it should be coming some time in November and most likely available on our 1.2/develop branch sometime in the next few weeks. It has a few precursors that need to be in place first but it shouldn't be too far away.

**Comment by jHoldroyd** [comment] 2012-12-06 11:33
Just as an update, this is almost done and is now available to test in the 1.2/develop branch

**Comment by chrisnharvey** [comment] 2012-12-22 17:28
Is this one finished @jHoldroyd?

**Comment by jHoldroyd** [comment] 2012-12-22 18:17
Just need to get the language strings merged for translations and a little more testing and it should be ready to go. Everything is now integrated with the rest of the orders system etc. so it's done but I'll close it when I've had a bit more time to go through things today.

**Comment by jHoldroyd** [comment] 2013-01-01 21:28
Closing as it should be finished now.

**Closed as completed by jHoldroyd** 2013-01-01 21:28 UTC
Labels: Feature Request

**Comment by yveveke** [comment] 2013-03-07 11:59
Can you explain somewhere how to use these variations?
I got single product, input or variation as a type in the backoffice. I tried them all, but don't see any change in the front.

Also editing a variation in the backoffice gives an error (product not found) upon saving.

**Comment by jHoldroyd** [comment] 2013-03-07 19:09
I'm not sure if you're using the default views or not but when you add modifiers and variants you should have dropdowns added to your product pages on the front end via the plugin firesale:modifier_form. This builds all of the options you set for a product and will let a user select sizes, colours, etc.

**Comment by yveveke** [comment] 2013-03-08 08:46
I found the mistake. The code for the modifiers is commented
File products_m.php Line 197

``` php
// Get variation and modifer data
$product['is_variation'] = $this->db->select('is_variation')->where('id', $product['id'])->get('firesale_products')->row()->is_variation;
// $product['modifiers']    = $this->pyrocache->model('modifier_m', 'product_variations', array($product['id'], $product['is_variation']), $this->firesale->cache_time);
```

**Comment by jHoldroyd** [comment] 2013-03-08 10:22
I think that may have been left in while I was debugging the multiple relationship field type issues, I'll get back in now. Sorry about that.

**Comment by yveveke** [comment] 2013-03-08 11:26
no problem, that's what the community is for.

**Comment by jHoldroyd** [comment] 2013-03-08 11:50
This is now fixed along with the modifier error that was being caused by streams. I found a workaround for it now Pyro 2.2 has officially been released.

**Comment by yveveke** [comment] 2013-03-08 11:59
Commit coming soon?

**Comment by jHoldroyd** [comment] 2013-03-08 12:44
It should be up already
