### ISSUE TITLE
FireSale Products widget issue

### ISSUE THREAD

**Issue by zaja** [firesale/firesale#225] opened 2012-11-30 15:29 UTC
Problem with FireSale Products widget, I have added widget to sidebar, set to show last 5 products from category, if I select NO in widget setting  "Show Sale Items", it display products in right column, but with PHP error on the top. If I select YES it not display any products as no product on sale under last 5.

Take a look: http://md-filtea.hr/

A PHP Error was encountered

Severity: Notice

Message: Trying to get property of non-object

Filename: user/field.user.php

Line Number: 124

**Comment by zaja** [comment] 2012-11-30 15:40
Error log:
ERROR - 2012-11-30 16:36:28 --> Severity: Notice  --> Trying to get property of non-object /home/mdfiltea/domains/md-filtea.hr/public_html/system/cms/modules/streams_core/field_types/user/field.user.php 124
ERROR - 2012-11-30 16:36:28 --> Severity: Notice  --> Trying to get property of non-object /home/mdfiltea/domains/md-filtea.hr/public_html/system/cms/modules/streams_core/field_types/user/field.user.php 125
ERROR - 2012-11-30 16:36:28 --> Severity: Notice  --> Trying to get property of non-object /home/mdfiltea/domains/md-filtea.hr/public_html/system/cms/modules/streams_core/field_types/user/field.user.php 126
ERROR - 2012-11-30 16:36:28 --> Severity: Notice  --> Trying to get property of non-object /home/mdfiltea/domains/md-filtea.hr/public_html/system/cms/modules/streams_core/field_types/user/field.user.php 127
ERROR - 2012-11-30 16:37:33 --> Plugin method "options" does not exist on class "Plugin_Theme".
ERROR - 2012-11-30 16:37:33 --> Severity: Notice  --> Trying to get property of non-object /home/mdfiltea/domains/md-filtea.hr/public_html/system/cms/modules/streams_core/field_types/user/field.user.php 124
ERROR - 2012-11-30 16:37:33 --> Severity: Notice  --> Trying to get property of non-object /home/mdfiltea/domains/md-filtea.hr/public_html/system/cms/modules/streams_core/field_types/user/field.user.php 125
ERROR - 2012-11-30 16:37:33 --> Severity: Notice  --> Trying to get property of non-object /home/mdfiltea/domains/md-filtea.hr/public_html/system/cms/modules/streams_core/field_types/user/field.user.php 126
ERROR - 2012-11-30 16:37:33 --> Severity: Notice  --> Trying to get property of non-object /home/mdfiltea/domains/md-filtea.hr/public_html/system/cms/modules/streams_core/field_types/user/field.user.php 127

**Comment by jHoldroyd** [comment] 2012-11-30 19:18
Which version of PyroCMS are you using?

**Comment by zaja** [comment] 2012-11-30 20:36
Latest 2.1.5, I have enabled widget so you can check errors on site:  http://md-filtea.hr/

**Comment by jHoldroyd** [comment] 2012-11-30 21:57
As I thought, the issue is actually one with the streams core, I submitted a pull request to fix it that you can find here: https://github.com/pyrocms/pyrocms/commit/5e2dba0c9a893e51d46d137ea274a6d73dcecffe 

For some reason it didn't make it into 2.1.5 but you can manually make the change (or I think it may be in it now). I'm closing this now, but hopefully you can get it sorted!

**Closed as completed** 2012-11-30 21:58 UTC

**Comment by zaja** [comment] 2012-11-30 22:03
Thanks, fixed. :)
