### ISSUE TITLE
jt database errors

### ISSUE THREAD

**Issue by yveveke** [firesale/firesale#293] opened 2013-03-15 11:32 UTC
I updated my firesale install file per file with the commits you guys did. Maybe the error lies there but I get the following errors when I create a product : 

``` php
A Database Error Occurred
Error Number: 1054

Unknown column 'shop_jt.row_id' in 'where clause'

SELECT * FROM `shop_firesale_products_firesale_categories` AS `jt` JOIN `shop_firesale_categories` ON `jt`.`firesale_categories_id` = `shop_firesale_categories`.`id` WHERE shop_jt.row_id = 5

A Database Error Occurred
Error Number: 1054

Unknown column 'shop_jt.row_id' in 'where clause'

UPDATE `shop_ci_sessions` SET `last_activity` = 1363346713, `user_data` = 'a:8:{s:8:\"username\";s:13:\"\";s:5:\"email\";s:21:\"\";s:2:\"id\";s:1:\"1\";s:7:\"user_id\";s:1:\"1\";s:8:\"group_id\";s:1:\"1\";s:5:\"group\";s:5:\"admin\";s:8:\"category\";N;s:17:\"flash:old:success\";s:36:\"A new product was added successfully\";}' WHERE shop_jt.row_id = 5 AND `session_id` = '7f593df18d4044e5db2480a0a42d8308'
```

**Comment by jHoldroyd** [comment] 2013-03-15 11:39
Duplicate of https://github.com/firesale/FireSale/issues/285

You need to update your Multiple field type to the latest 2.0/develop version or delete it from your pyrostreams install and let it fallback to the version included with FireSale 1.2

**Closed as completed by jHoldroyd** 2013-03-15 11:39 UTC
Labels: Duplicate
