### ISSUE TITLE
Long list of errors on orders page when a user is deleted

### ISSUE THREAD

**Issue by chrisnharvey** [firesale/firesale#51] opened 2012-08-13 10:13 UTC
When a user is deleted, the orders page in the backend shows a long list of errors when trying to access the user object.

**Comment by jHoldroyd** [comment] 2012-08-26 11:03
Should be fixed now.

**Comment by chrisnharvey** [comment] 2012-09-13 13:40
Still getting this issue. Reopening.

**Comment by jHoldroyd** [comment] 2012-09-17 19:34
Filed a pull request for the 2.2 develop branch of Pyro to take care of this issue. It's not specifically anything to do with FireSale but is caused by the streams_core user field type and should hopefully be accepted.

It can be viewed here: https://github.com/pyrocms/pyrocms/pull/1862

Closing this now

**Closed as completed by jHoldroyd** 2012-09-17 19:34 UTC
Labels: Bug
