### ISSUE TITLE
PayPal Express redirects back to the site but doesn't collect money?

### ISSUE THREAD

**Issue by joshuarlowry** [firesale/firesale#241] opened 2012-12-11 18:24 UTC
After I click pay it goes to PayPal.  I log in.  I choose my payment method and click the Pay Now button.  Paypal appears to go to the review your order page but then redirects back to my site.

http://SITE/cart/success?token=...&PayerID=...

Payment was not collected.  Ideas?  I'm in real trouble here... I don't know even where to begin.

**Comment by joshuarlowry** [comment] 2012-12-11 18:50
Calling PayPal support.  Seems like it might be their issue.  Unsure.

**Comment by joshuarlowry** [comment] 2012-12-11 19:04
Confirmed with paypal that website is not sending the response after returning as a success to complete the transaction.  This might be something that we modified.  Investigating now.

**Comment by jHoldroyd** [comment] 2012-12-11 20:19
I'll leave this open until you can confirm where the issue is

**Comment by chrisnharvey** [comment] 2012-12-11 21:39
Looks like there is a slight issue with this. I'm putting together a fix now. Apologies for the inconvenience.

**Comment by joshuarlowry** [comment] 2012-12-12 00:13
Find anything?  We are working to release this functionality tomorrow.

**Comment by ghost** [comment] 2012-12-12 03:35
So, here is what we did:

``` php
   function success()
   {
        if($order_id = $this->session->userdata('order_id'))
        {
           $order = $this->orders_m->get_order_by_id($order_id);

           if (!empty($order) AND $this->gateways->is_enabled($order['gateway']['id']))
           {
              // Get the gateway slug
              $gateway = $this->gateways->slug_from_id($order['gateway']['id']);

              // Initialize CI-Merchant
              $this->merchant->load($gateway);
              $this->merchant->initialize($this->gateways->settings($gateway));

              $params = array(
                    'currency'  => $this->fs_cart->currency()->cur_code,
                    'amount'         => $this->fs_cart->total() + $order['shipping']['price'],
                    'order_id'       => $order_id,
                    'transaction_id' => $order_id,
                    'reference'      => 'Order #' . $order_id,
                    'description'    => 'Order #' . $order_id,
                    'first_name'     => $order['bill_to']['firstname'],
                    'last_name'      => $order['bill_to']['lastname'],
                    'address1'       => $order['ship_to']['address1'],
                    'address2'       => $order['ship_to']['address2'],
                    'city'           => $order['ship_to']['city'],
                    'region'         => $order['ship_to']['county'],
                    'country'        => $order['ship_to']['country']['code'],
                    'postcode'       => $order['ship_to']['postcode'],
                    'phone'          => $order['ship_to']['phone'],
                    'email'          => $order['ship_to']['email'],
              );

            $response = $this->merchant->purchase_return($params);

            if ($response->status() == Merchant_response::COMPLETE)
            {
               $this->orders_m->update_status($order_id, 2);

               // Email the user
               Events::trigger('email', array_merge($order,
                  array('slug' => 'order-complete-user', 'to' => $order['bill_to']['email'])), 'array');

               // Email the admin
               Events::trigger('email', array_merge($order,
                  array('slug' => 'order-complete-admin', 'to' => $this->settings->get('contact_email'))), 'array');

               $this->fs_cart->destroy();
            }
            else
            {
               $this->session->set_flashdata('error', 'Order did not complete successfully. Status = '.$response->status().'. Please contact the admin.');
               redirect('cart/payment/'.$order_id);
            }

            $this->template->title(lang('firesale:payment:title_success'))
                           ->set_breadcrumb(lang('firesale:cart:title'), $this->routes_m->build_url('cart'))
                           ->set_breadcrumb(lang('firesale:checkout:title'), $this->routes_m->build_url('cart').'/checkout')
                           ->set_breadcrumb(lang('firesale:payment:title'), $this->routes_m->build_url('cart').'/payment')
                           ->set_breadcrumb(lang('firesale:payment:title_success'), $this->routes_m->build_url('cart').'/payment')
                           ->build('payment_complete', $order);
           }
           else
           {
              $this->session->set_flashdata('Error. Please contact the site admin.');
           }
        }
        else
        {
            show_404();
        }
   }
```

This is NOT a generic solution.  There is some error checking and things that need to be done... like the $params area was basically just a copy from purchase (not sure what generically is needed here) and

**Comment by ghost** [comment] 2012-12-12 03:37
As far as we are concerned, we are going to use this until you all have 1.1.3 out (where you move the payment processing away from the cart).

**Comment by jHoldroyd** [comment] 2012-12-12 09:13
I'm happy you've found a solution, I'll see what Chris has to say about this and see if there's anything more permenant as 1.3.0 is still a while away.

**Comment by jcastillotx** [comment] 2013-01-22 19:18
what file is this located at

**Comment by jHoldroyd** [comment] 2013-01-22 19:45
That looks like controllers/front_cart.php

**Comment by jHoldroyd** [comment] 2013-02-18 17:00
This should have finally been fixed with a commit a few days ago.

**Closed as completed by jHoldroyd** 2013-02-18 17:00 UTC
