### ISSUE TITLE
Product Attributes

### ISSUE THREAD

**Issue by iknowfoobar** [firesale/firesale#350] opened 2013-05-22 17:52 UTC
I was wondering if you had any documentation on the product attributes? It is something I need for a project which we are using Firesale for.

I can list the attributes on the product page however is it possible to use them as filters? For example I am viewing a category page but would only like to see all products that are of colour blue?

**Comment by jHoldroyd** [comment] 2013-05-23 09:11
Unfortunately there wasn't a way to do this already, and the only real way for us to do it is with the plugin. I've added it since it'll come in handy down the road but as for in the pages themselves there's not much in the way of filtering. We have done filtered navigation based on a range of options that can be customised, but again that's not for the product/category pages it was designed as it's own page where we can manage everything.

If you are interested in the plugin, you can do it a few different ways, firstly:

``` php
{{ firesale:products attribute="colour = blue" }}
...
{{ /firesale:products }}
```

You can also do more/less than, and equals to but it still needs the extra = sign, like so:

``` php
>  {{ firesale:products attribute="size >= 8" }}
>= {{ firesale:products attribute="size >== 8" }}
<  {{ firesale:products attribute="size <= 8" }}
<= {{ firesale:products attribute="size <== 8" }}
```

You can also do multiple attributes:

``` php
{{ firesale:products attribute1="colour = blue" attribute_2="size >== 8" }}
...
{{ /firesale:products }}
```

Hope that covers what you need, if not I'll keep looking into options but chances are the filtered navigation module that's coming out soon.

**Comment by iknowfoobar** [comment] 2013-05-23 09:48
Thanks, it is good to know about the plugin but it isn't really what I required. It sounds like I would be interested in the Navigation Module though. Can you give any details on when that is coming out?

**Comment by iknowfoobar** [comment] 2013-05-24 08:43
Would you guys mind if I had a look at building something like this in the attributes_module?

I was thinking maybe a plugin that would extract a list of available attributes and their values for the category and subcategories that are currently being viewed. The user could then tick the values they require to filter by.

The front_category controller could then detect if the attributes module is installed and add the selected attribute filters into the products query?

**Comment by jHoldroyd** [comment] 2013-05-24 13:15
By all means feel free to add that, we're always happy to get contributions and that sounds like a cool little feature. Like I said we do have something for this that works on product fields currently in alpha but if you want to add it to attributes it sounds great. You could also turn it into a controller that is part of attributes so it comes with a pre-built view.

**Comment by jHoldroyd** [comment] 2013-05-24 19:36
Since you're working on this I'm just going to close it

**Closed as completed by jHoldroyd** 2013-05-24 19:36 UTC
