### ISSUE TITLE
A Database Error Occurred Error Number: 1054 Unknown column 'default_jt.row_id' in 'where clause'

### ISSUE THREAD

**Issue by firecod3x** [firesale/firesale#300] opened 2013-03-17 16:24 UTC
PyroCMS 2.2 and FireSale 1.2

http://localhost/dev/cms/pyrocms/2.2/admin/firesale/products/edit/1

A Database Error Occurred

Error Number: 1054

Unknown column 'default_jt.row_id' in 'where clause'

SELECT \* FROM `default_firesale_products_firesale_categories` AS `jt` JOIN `default_firesale_categories` ON `jt`.`firesale_categories_id` = `default_firesale_categories`.`id` WHERE default_jt.row_id = 1

**Comment by jHoldroyd** [comment] 2013-03-17 16:59
Duplicate of #285

You need to update your Multiple field type to the latest 2.0/develop version or delete it from your pyrostreams install and let it fallback to the version included with FireSale 1.2

**Closed as completed by jHoldroyd** 2013-03-17 16:59 UTC
Labels: Duplicate
