### ISSUE TITLE
DB error on product edit

### ISSUE THREAD

**Issue by iknowfoobar** [firesale/firesale#306] opened 2013-03-21 10:16 UTC
Firesale v1.2 and PyroCMS Pro v2.2.0

Whenever I try to edit a product I always get the following fatal error:

Error Number: 1054

Unknown column 'default_jt.row_id' in 'where clause'

SELECT \* FROM `default_firesale_products_firesale_categories` AS `jt` JOIN `default_firesale_categories` ON `jt`.`firesale_categories_id` = `default_firesale_categories`.`id` WHERE default_jt.row_id = 1

**Comment by jHoldroyd** [comment] 2013-03-21 10:21
Duplicate of #285

This is caused by an outdated Multiple field type, either upgrade the version you already have (generally included with the Streams GUI in Pro) or delete it and it will fallback to using the correct version that is packaged with FireSale

**Closed as completed by jHoldroyd** 2013-03-21 10:21 UTC
Labels: Duplicate

**Comment by iknowfoobar** [comment] 2013-03-21 10:27
Ok, thanks, but just so you are aware I am using the latest version of Pro, only downloaded it yesterday.

**Comment by jHoldroyd** [comment] 2013-03-21 10:30
Yeah that's not the issue, with the 2.2 release they didn't update the multiple field type to a version that actually works with 2.2, it's the old version from 2.1.5.

2.0/develop is the version we helped to fix but wasn't included for some reason, however it is packaged with FireSale so simply deleting the version in the core will fallback to ours and continue to work for both FireSale and other modules.

**Comment by iknowfoobar** [comment] 2013-03-21 11:43
Thanks, I have read the duplicate issue and all is clear now :)
